### ISSUE TITLE
implement caching

### ISSUE THREAD

**Issue by marwan-at-work** [stamblerre/gocode#10]
Thank you for all the work on gocode to make auto completion fast :) 

After chatting with @ramya-rao-a, I noticed that the caching stuff that you did, which really helps auto completion speeds, is only merged in mdempsky's fork and not this one (and therefore auto completion in go modules is still pretty slow). So

1. I was wondering if it's possible to "just merge the cache stuff here"? 
2. If not, where should we keep an eye on for updates on gocode in go modules?

**Comment by stamblerre** [comment]
Unfortunately, I can't merge the caching stuff here because it's a bit different from how go/packages works. However, I can investigate a caching approach here to improve things. Not sure what the timeline will be, but we can leave this as a tracking issue.

**Comment by stamblerre** [comment]
Closing this issue, as the current recommendation for autocompletion is to use [`gopls`](https://github.com/golang/tools/blob/master/gopls/README.md).
