### ISSUE TITLE
Vim setup paths

### ISSUE THREAD

**Issue by jeroenrinzema** [stamblerre/gocode#12]
I just noticed and suspect that the `Vim` installation paths are incorrect.
Shouldn't:
`Plug 'mdempsky/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }`
Be?:
`Plug 'stamblerre/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }`

**Comment by stamblerre** [comment]
Fixed with https://github.com/stamblerre/gocode/commit/2c62dd5df32d994e6078e55fa9b09937cd9e1bdf. Thanks!
