### ISSUE TITLE
merge stamblerre/gocode and mdempsky/gocode (in the same way as godef)

### ISSUE THREAD

**Issue by VojtechVitek** [stamblerre/gocode#24]
Hi,
I just wonder if you guys are planning to submit the changes upstream to github.com/mdempsky/gocode, or if you plan to maintain this repo separately.

Is there any roadmap?

Thanks for your hard work!

Cheers,
- Vojtech

**Comment by stamblerre** [comment]
The Go tools team is currently working on [golang.org/x/tools/cmd/golsp](https://golang.org/x/tools/cmd/golsp), which will be the eventual replacement for gocode (and will work in modules). In the meantime, we are maintaining separate forks, although it should be possible to merge them in the same way that godef has been merged. If I get a chance, I will try to do that.

**Comment by VojtechVitek** [comment]
Thanks a lot!

**Comment by zippoxer** [comment]
> 
> 
> The Go tools team is currently working on [golang.org/x/tools/cmd/golsp](https://golang.org/x/tools/cmd/golsp), which will be the eventual replacement for gocode (and will work in modules). In the meantime, we are maintaining separate forks, although it should be possible to merge them in the same way that godef has been merged. If I get a chance, I will try to do that.

Cool! I didn't know the Go team is working on a replacement. I almost lost hope for VS Code for Go due to annoying suggestion lags, so thanks for letting me know 👍

**Comment by stamblerre** [comment]
Closing this issue, as the current recommendation for autocompletion is to use [`gopls`](https://github.com/golang/tools/blob/master/gopls/README.md).
