### ISSUE TITLE
How can this fork be much faster than the origin?

### ISSUE THREAD

**Issue by Stumble** [stamblerre/gocode#27]
### What version of Go are you using (`go version`)?
go version go1.11.5 linux/amd64

just out of curiosity, I am using Emacs with company-go,and  when I use the gocode from mdempsky/gocode with -cache, the completion was sometimes slow and sometimes got suck, though very accurate. I heard this fork from vscode-go and it's extremely fast! 

Is there any trade-off in accuracy v.s. speed or some bug get fixed?

Thanks for providing such good completion experience :+1:

**Comment by stamblerre** [comment]
I'm not sure how it could be the case that the different forks have significantly different speeds. In any case, the current recommendation for autocompletion is [`gopls`](https://github.com/golang/tools/blob/master/gopls/README.md), which has a cache and is therefore quite fast.

**Comment by Stumble** [comment]
yeah, switched to gopls serveral momths ago, not quite stable, but keeps
getting better. Thanks for the work!
