### ISSUE TITLE
External packages no autocomplete

### ISSUE THREAD

**Issue by FourSeventy** [stamblerre/gocode#29]
### What version of Go are you using (`go version`)?
go version go1.12 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mike/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mike/development/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mike/development/thought-ops/matcher-stream/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6q/yt_hgwkx7950h3w3thf4_49r0000gn/T/go-build541360341=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What is the debug output of `gocode`?

2019/03/04 19:27:25 gbimporter: no package found for github.com/Shopify/sarama: can't find import: "github.com/Shopify/sarama"

2019/03/04 19:27:25 gbimporter: no package found for github.com/movio/kasper: can't find import: "github.com/movio/kasper"

### What editor are using?
neovim

I am unable to get any autocomplete suggestions from external packages. Standard library packages like 'fmt' autocomplete fine. My project uses go modules and is located outside of the $GOPATH. When I look at the debug output i see 

gbimporter: no package found for github.com/Shopify/sarama: can't find import: "github.com/Shopify/sarama"

I have `go install`ed all of my dependencies as well as my project. It seems like it might have to do with my environment but I can't figure out what the problem is.

**Comment by stamblerre** [comment]
Are you sure you are using this version of gocode? The error message sounds like something that would come out of [github.com/mdemspky/gocode](https://github.com/mdempsky/gocode).

**Comment by FourSeventy** [comment]
Crap you are right. I was trying so many versions of gocode that I got confused about which version I had installed. Sorry about that.
