### ISSUE TITLE
no results for unimported packages when using Go modules

### ISSUE THREAD

**Issue by stamblerre** [stamblerre/gocode#3]
In the below case we dont get any completions.

```
import (
        "rsc.io/quote"
        "fmt"
)

func main() {
        fmt.Println("hello")
        quote.
}
```
Update the quote. above to quote.Hello(), save the file. The next time auto-completions work

```
import (
        "rsc.io/quote"
        "fmt"
)

func main() {
        fmt.Println("hello")
        quote.Hello();
        quote.
}
```

**Comment by uudashr** [comment]
Do we have progress? Had same issue on vscode-go. Please tell me if there is anything that I can help

**Comment by stamblerre** [comment]
This is going to require some underlying changes to the go/packages API, so it probably won't be fixed very soon. The current approach is just to save the file and then the completions will work.

**Comment by broady** [comment]
I don't get any completions working.

go.mod:
```
module github.com/broady/junk/gocodetest

require rsc.io/quote v1.5.2
```

main.go:
```
package main

import (
	"fmt"

	"rsc.io/quote"
)

func main() {
	fmt.Println("hello")
	quote.Hello()
}
```

Log output:
```
$ gocode -s -debug
2018/10/29 21:45:10 Got autocompletion request for '/Users/cbro/src/github.com/broady/junk/gocodetest/main.go'
2018/10/29 21:45:10 Cursor at: 96
2018/10/29 21:45:10 -------------------------------------------------------
package main

import (
	"fmt"

	"rsc.io/quote"
)

func main() {
	fmt.Println("hello")
	quote.Hel#
}
2018/10/29 21:45:10 -------------------------------------------------------
2018/10/29 21:45:10 Elapsed duration: 207.048µs
2018/10/29 21:45:10 Offset: 0
2018/10/29 21:45:10 Number of candidates found: 0
2018/10/29 21:45:10 Candidates are:
2018/10/29 21:45:10 =======================================================
```

Installed with `go get -u github.com/stamblerre/gocode`
(built at 12640289f65065d65)

**Comment by ramya-rao-a** [comment]
@stamblerre I believe this can be closed, correct?

**Comment by stamblerre** [comment]
@ramya-rao-a: I don't believe this has been resolved yet.

**Comment by stamblerre** [comment]
This should be fixed as of https://github.com/stamblerre/gocode/commit/2f9d39d8f31d7c82b3cd12961d77d9ea3fdad69b.

**Comment by nezorflame** [comment]
Works, thanks a lot!
