### ISSUE TITLE
Contextually autocomplete structs properties

### ISSUE THREAD

**Issue by hook-s3c** [stamblerre/gocode#30]
`go 1.10.4 linux/amd64`

Hi, I raised an issue on deoplete-go, an autocomplete integration for NeoVim's support for Golang.

I'm having trouble auto-completing for the properties of Structs when I build out variables.

Let me know what I need to do here and I'll get back to you.

https://github.com/deoplete-plugins/deoplete-go/issues/149

**Comment by stamblerre** [comment]
I don't think gocode does completion of struct fields when you are creating one. I will happily accept a PR, but [gopls](https://golang.org/x/tools/cmd/gopls) should be able to do this for you.

**Comment by stamblerre** [comment]
Closing this issue, as the current recommendation for autocompletion is to use [`gopls`](https://github.com/golang/tools/blob/master/gopls/README.md).
