### ISSUE TITLE
nil pointer panic when autocompleting

### ISSUE THREAD

**Issue by firelizzard18** [stamblerre/gocode#31]
Please answer these questions before submitting your issue. Thanks!
Also, remember that to restart gocode, you have to run `gocode close`.

### What version of Go are you using (`go version`)?

```
go version go1.12 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

<details>
<summary><code>go env</code></summary>
<pre><code>GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/me/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vy/7b8vfhcx2v7036h99kzs188h0000gn/T/go-build561165587=/tmp/go-build -gno-record-gcc-switches -fno-common"
</code></pre>
</details>

### What is the debug output of `gocode`?

`/go/bin/gocode-gomod -s -debug -sock unix -addr 127.0.0.1:37373`

I modified the source in the output. The error occurs in `helloWorld` at `req.` in this particular case.

```
2019/03/08 23:17:11 Got autocompletion request for '/usr/src/web/website/serve/main.go'
2019/03/08 23:17:11 Cursor at: 856
2019/03/08 23:17:11 -------------------------------------------------------
package main

import (
        "fmt"
        "log"
        "net/http"
)

func helloWorld(resp http.ResponseWriter, req *http.Request) {
        fmt.Fprintf(resp, "Hello world")

        req.
}

func main() {
        http.Handle("/", http.FileServer(http.Dir(os.Args[1])))

        http.HandleFunc("/hi", func(resp http.ResponseWriter, req *http.Request) {
                fmt.Fprintf(resp, "Hello world")
        })

        err = http.ListenAndServe(":80", nil)
        if err != nil {
                log.Println(err)
        }
}
2019/03/08 23:17:11 -------------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 22 [running]:
runtime/debug.Stack(0xb, 0xc0001b7438, 0x1)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc0000c1260)
        /go/src/github.com/stamblerre/gocode/server.go:78 +0x94
panic(0x144ad60, 0x1837cc0)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
github.com/stamblerre/gocode/internal/suggest.(*Config).analyzePackage(0xc0001b7a98, 0xc0000a8140, 0x3c, 0xc0001c0000, 0x5df, 0x5df, 0x358, 0x0, 0x0, 0x700, ...)
        /go/src/github.com/stamblerre/gocode/internal/suggest/suggest.go:128 +0x251
github.com/stamblerre/gocode/internal/suggest.(*Config).Suggest(0xc0001b7a98, 0xc0000a8140, 0x3c, 0xc0001c0000, 0x5df, 0x5df, 0x358, 0x10ab3bf, 0x1847480, 0x1469660, ...)
        /go/src/github.com/stamblerre/gocode/internal/suggest/suggest.go:55 +0xb5
main.(*Server).AutoComplete(0x1865460, 0xc0000adbc0, 0xc0000c1260, 0x0, 0x0)
        /go/src/github.com/stamblerre/gocode/server.go:104 +0x138
reflect.Value.call(0xc0000ba720, 0xc0000b8588, 0x13, 0x14c52ad, 0x4, 0xc000062f18, 0x3, 0x3, 0xc0000ada00, 0x1422780, ...)
        /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:447 +0x449
reflect.Value.Call(0xc0000ba720, 0xc0000b8588, 0x13, 0xc000051718, 0x3, 0x3, 0x1494d00, 0x14a5401, 0xc0000ad940)
        /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc0000ad8c0, 0xc00014c000, 0xc0000aa628, 0xc0000aa650, 0xc00018c100, 0xc0000c0ca0, 0x140e980, 0xc0000adbc0, 0x16, 0x140e940, ...)
        /usr/local/Cellar/go/1.11.1/libexec/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
        /usr/local/Cellar/go/1.11.1/libexec/src/net/rpc/server.go:481 +0x47e
```

### What (client-side) flags are you passing into `gocode`?

No clue.

### What editor are using?

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:16:38.656Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
aurelia|Aur|1.0.3
Aurelia|beh|1.2.2
better-toml|bun|0.3.2
vscode-opennewinstance|chr|0.0.4
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.5.1
permute-lines|ear|0.0.10
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.7.0
gitlab-workflow|fat|2.0.1
easy-icons|jam|0.3.1
vscode-sshfs|Kel|1.13.0
mssql|ms-|1.4.0
cpptools|ms-|0.21.0
csharp|ms-|1.17.1
Go|ms-|0.9.2
mono-debug|ms-|0.15.8
PowerShell|ms-|1.11.0
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.5.2
material-icon-theme|PKi|3.6.3
vscode-icons|rob|8.2.0
rewrap|stk|1.9.1
code-spell-checker|str|1.6.10
vsc-prompt|fir|0.0.1
vscode-arduino|vsc|0.2.25

(2 theme extensions excluded)

</details>

**Comment by stamblerre** [comment]
What commit is your gocode built at?

**Comment by firelizzard18** [comment]
I'm not completely sure, since VSCode's Go extension handles everything. I think `vscode-go` just pulls the latest from GitHub, which is up to date on my machine:

```
% git -C $GOPATH/src/github.com/stamblerre/gocode log -1
commit 8cc90faaf4765d16de060350da41eadccc1a15d1 (HEAD -> master, origin/master, origin/HEAD)
Merge: e620fbf dbe18d8
Author: Rebecca Stambler <rstambler@golang.org>
Date:   Tue Feb 12 21:23:08 2019 -0500

    gocode: cancel when the main context is done, as well
    
    Merge pull request #26 from tekkamanendless/cancel-case
```

**Comment by stamblerre** [comment]
Hm, it's just strange because the line number in the stack trace only has a call to `context.Background()`, which shouldn't cause a nil pointer. Can you reproduce this?

**Comment by firelizzard18** [comment]
I guess `gocode-gomod` was an older version. When I ran `go install github.com/stamblerre/gocode` and manually renamed it to `gocode-gomod`, it started working.
