### ISSUE TITLE
Feature request: goimports support in Sublime Text plugin

### ISSUE THREAD

**Issue by imax9000** [stamblerre/gocode#36]
Please add support for running `goimports` instead of `gofmt` on save.

A viable alternative - add an option to disable running `gofmt` on save entirely and let users use other plugins for code formatting.

**Comment by christopher-dG** [comment]
This package is only for autocompletion, you should be looking for this setting in the generic Go support layer for your editor (e.g. [go-mode](https://github.com/dominikh/go-mode.el) for Emacs, maybe [this](https://github.com/DisposaBoy/GoSublime) for Sublime).

**Comment by imax9000** [comment]
FYI, `goimports` is a drop-in replacement for `gofmt` that automatically adds import lines. It doesn't do any autocompletion :)

E.g. if there was a configuration knob to specify a command to run on save, instead of hardcoded `gofmt`, that would do the trick already.

**Comment by stamblerre** [comment]
The editor-specific plugins in this repository are relics from https://github.com/nsf/gocode. The current recommendation for editor integration is using a specific plugin (like GoSublime, suggested above), or an LSP plugin with [`gopls`](https://github.com/golang/tools/blob/master/gopls/README.md). For Sublime, I believe https://github.com/tomv564/LSP works.
