### ISSUE TITLE
not working with vim 8.1

### ISSUE THREAD

**Issue by laoshaw** [stamblerre/gocode#38]
I added :  Plug 'stamblerre/gocode', {'rtp': 'vim/', 'do': '~/.vim/plugged/gocode/vim/symlink.sh'} to .vimrc and installed it, vim-go works fine but gocode does not, there is no autocomplete, do I need do anything extra other than PlugInstall it? I made sure GOPATH,PATH, and 'go get -u github.com/stamblerre/gocode' are done correctly. Do I need type any key to bring up the autocomplete dropdown list?

I'm using go1.13beta1.

**Comment by stamblerre** [comment]
I am not very familiar with Vim, but I believe that the usual completion keybinding is `<C-x><C-o>`.
