### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by logeable** [stamblerre/gocode#4]
## build failed

src/github.com/stamblerre/gocode/internal/suggest/suggest.go:138:3: cannot use func literal (type func(*token.FileSet, string) (*ast.File, error)) as type func(*token.FileSet, string, []byte) (*ast.File, error) in field value

[packages.Config.ParseFile](https://github.com/golang/tools/blob/master/go/packages/packages.go#L108)

**Comment by alexkreidler** [comment]
Same issue:
```
$ go get github.com/stamblerre/gocode
# github.com/stamblerre/gocode/internal/suggest
go/src/github.com/stamblerre/gocode/internal/suggest/suggest.go:138:3: cannot use func literal (type func(*token.FileSet, string) (*ast.File, error)) as type func(*token.FileSet, string, []byte) (*ast.File, error) in field value
```
Thanks for helping with a fork

**Comment by alexkreidler** [comment]
It looks like the error is coming from a breaking change in `golang/tools` 5 days ago. Here is the commit: https://github.com/golang/tools/commit/2f1727f1b37d7d257665debc72d4ae0b8e449748#diff-04792145c70ebd708928684da4875fe9R108

**Comment by win-t** [comment]
haha, it's funny when the golang team forces everyone to follow _import compatibility rule_, but then, they are the one who broke this rule.

**Comment by tonka3000** [comment]
So we have to wait to get it fixed?

**Comment by tyhi** [comment]
@stamblerre fixed it with 00b5ffcd8b84cfd1ecb922016a778abfa3d414bc. Builds for me now.

**Comment by stamblerre** [comment]
Sorry about not fixing this earlier--somehow didn't get a notification for this. Should be fixed now.

**Comment by CarrieKroutil** [comment]
Upgrading to go 1.11.1 fixed this issue for me.
