### ISSUE TITLE
I need Autobuild !!

### ISSUE THREAD

**Issue by laomobk** [stamblerre/gocode#42]
Please answer these questions before submitting your issue. Thanks!
Also, remember that to restart gocode, you have to run `gocode close`.

### What version of Go are you using (`go version`)?

1.13
### What operating system and processor architecture are you using (`go env`)?
Arch ARM

### What is the debug output of `gocode`?
Nope.

Run `gocode close` and then run `gocode -s -debug` to restart gocode in debug mode. 
Try to complete once again from your editor, and paste the output printed by gocode here.

### What (client-side) flags are you passing into `gocode`?

Please note here if you are using `-source`, `-builtin`, `-ignore-case`, `-unimported-packages`, or `-fallback-to-source`.

### What editor are using?

Anyway, nsf/gocode has this future, but this version is not available . So that I can't get Completion suggestions in time when I just modify and save a file.

**Comment by stamblerre** [comment]
As stated in the [README](https://github.com/stamblerre/gocode#important-this-fork-of-gocode-is-currently-in-maintenance-mode-for-a-better-development-experience-with-go-modules-we-suggest-you-use-the-go-language-server-gopls), this version of `gocode` is currently in maintenance mode, so new features will not be added. [`gopls`](https://github.com/golang/tools/blob/master/gopls/README.md) operates on files as they change, even if they are not saved, so I suggest you try that as an alternative.
