### ISSUE TITLE
go get build error

### ISSUE THREAD

**Issue by notatestuser** [stamblerre/gocode#8]
Hi, looks like the latest master doesn't install through `go get`.

```bash
$ go get -u github.com/stamblerre/gocode
# github.com/stamblerre/gocode/internal/suggest
../../go/pkg/mod/github.com/stamblerre/gocode@v0.0.0-20181016172724-12640289f650/internal/suggest/suggest.go:130:3: cannot use func literal (type func(*token.FileSet, string, []byte) (*ast.File, error)) as type func(*token.FileSet, string) (*ast.File, error) in field value
```

### What version of Go are you using (`go version`)?

go1.11.1 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

macOS 10.14 Mojave

**Comment by stamblerre** [comment]
Based on the error message, I think you need to update your version of golang.org/x/tools, because the go/packages API changed to include a 3rd parameter in that function.

**Comment by notatestuser** [comment]
Ah, I had overlooked that with being in a bit of a hurry at the time. Thanks and apologies for the issue.
